"""device secret_lines

Revision ID: 1e85a63cc383
Revises: cebc76f1126a
Create Date: 2026-07-12 03:35:42.026199

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '1e85a63cc383'
down_revision: str | None = 'cebc76f1126a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('secret_lines', sa.JSON(), nullable=False, server_default='[]')
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_column('secret_lines')

    # ### end Alembic commands ###
