"""staged imports

Revision ID: cd21cb24107b
Revises: 1e85a63cc383
Create Date: 2026-07-13 05:25:49.567966

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'cd21cb24107b'
down_revision: str | None = '1e85a63cc383'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staged_imports',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('proposal', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('staged_imports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staged_imports_workspace_id'), ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staged_imports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staged_imports_workspace_id'))

    op.drop_table('staged_imports')
    # ### end Alembic commands ###
