"""initial schema

Revision ID: cebc76f1126a
Revises: 
Create Date: 2026-07-12 01:56:15.379835

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'cebc76f1126a'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workspaces',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('imports',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('warning_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('log', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('imports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_imports_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('snapshots',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('import_id', sa.String(length=32), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('batfish_snapshot_name', sa.String(length=200), nullable=True),
    sa.Column('analysis_status', sa.String(length=40), nullable=False),
    sa.Column('device_count', sa.Integer(), nullable=False),
    sa.Column('warning_count', sa.Integer(), nullable=False),
    sa.Column('parse_error_count', sa.Integer(), nullable=False),
    sa.Column('completeness_score', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'display_name', name='uq_snapshot_name')
    )
    with op.batch_alter_table('snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_snapshots_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('devices',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('snapshot_id', sa.String(length=32), nullable=False),
    sa.Column('hostname', sa.String(length=200), nullable=False),
    sa.Column('vendor', sa.String(length=50), nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=True),
    sa.Column('os_family', sa.String(length=30), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('management_ip', sa.String(length=45), nullable=True),
    sa.Column('source_filename', sa.String(length=500), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('parse_status', sa.String(length=30), nullable=False),
    sa.Column('warning_count', sa.Integer(), nullable=False),
    sa.Column('parse_warnings', sa.JSON(), nullable=False),
    sa.Column('completeness_score', sa.Float(), nullable=False),
    sa.Column('raw_config', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'hostname', name='uq_device_hostname')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_hostname'), ['hostname'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_snapshot_id'), ['snapshot_id'], unique=False)

    op.create_table('acls',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('device_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('evidence_lines', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'name', name='uq_acl_name')
    )
    with op.batch_alter_table('acls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_acls_device_id'), ['device_id'], unique=False)

    op.create_table('interfaces',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('device_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('layer_role', sa.String(length=10), nullable=False),
    sa.Column('admin_state', sa.String(length=10), nullable=False),
    sa.Column('switchport_mode', sa.String(length=20), nullable=True),
    sa.Column('access_vlan', sa.Integer(), nullable=True),
    sa.Column('native_vlan', sa.Integer(), nullable=True),
    sa.Column('trunk_allowed_vlans', sa.String(length=500), nullable=True),
    sa.Column('ip_addresses', sa.JSON(), nullable=False),
    sa.Column('vrf', sa.String(length=100), nullable=True),
    sa.Column('acl_in', sa.String(length=200), nullable=True),
    sa.Column('acl_out', sa.String(length=200), nullable=True),
    sa.Column('evidence_lines', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'name', name='uq_interface_name')
    )
    with op.batch_alter_table('interfaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interfaces_device_id'), ['device_id'], unique=False)

    op.create_table('static_routes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('device_id', sa.String(length=32), nullable=False),
    sa.Column('vrf', sa.String(length=100), nullable=True),
    sa.Column('prefix', sa.String(length=50), nullable=False),
    sa.Column('next_hop_ip', sa.String(length=45), nullable=True),
    sa.Column('next_hop_interface', sa.String(length=100), nullable=True),
    sa.Column('admin_distance', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('evidence_lines', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('static_routes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_static_routes_device_id'), ['device_id'], unique=False)

    op.create_table('vlans',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('device_id', sa.String(length=32), nullable=False),
    sa.Column('vlan_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('evidence_lines', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'vlan_id', name='uq_vlan_id')
    )
    with op.batch_alter_table('vlans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vlans_device_id'), ['device_id'], unique=False)

    op.create_table('acl_entries',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('acl_id', sa.String(length=32), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('protocol', sa.String(length=20), nullable=True),
    sa.Column('src', sa.JSON(), nullable=True),
    sa.Column('dst', sa.JSON(), nullable=True),
    sa.Column('src_port', sa.JSON(), nullable=True),
    sa.Column('dst_port', sa.JSON(), nullable=True),
    sa.Column('established', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['acl_id'], ['acls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('acl_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_acl_entries_acl_id'), ['acl_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('acl_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_acl_entries_acl_id'))

    op.drop_table('acl_entries')
    with op.batch_alter_table('vlans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vlans_device_id'))

    op.drop_table('vlans')
    with op.batch_alter_table('static_routes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_static_routes_device_id'))

    op.drop_table('static_routes')
    with op.batch_alter_table('interfaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interfaces_device_id'))

    op.drop_table('interfaces')
    with op.batch_alter_table('acls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_acls_device_id'))

    op.drop_table('acls')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_devices_hostname'))

    op.drop_table('devices')
    with op.batch_alter_table('snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_snapshots_workspace_id'))

    op.drop_table('snapshots')
    with op.batch_alter_table('imports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_imports_workspace_id'))

    op.drop_table('imports')
    op.drop_table('workspaces')
    op.drop_table('jobs')
    # ### end Alembic commands ###
